### ISSUE TITLE
Major log spam caused by failing to set EMC values to various items

### ISSUE THREAD

**Issue by ImperatorStorm** [FTBTeam/Equivalent-Exchange#2]
### Mod version

1.20.4-1.0.3

### Forge / Fabric version

Neoforge 20.4.237

### Modpack & version

Neotech 1.3.0

### What issue are you having?

Equivalent Exchange appears to be spamming tens of thousands of lines in my `latest.log` as it fails to assign EMC values to various items.

### Crashlogs

https://mclo.gs/yR2PmNk

### Steps to reproduce

1. Load into (and play in?) a world.
2. Watch as `latest.log` file is filled.

**Comment by gigabit101** [comment]
Fixed in 1.0.4
