### ISSUE TITLE
Transmutation Table

### ISSUE THREAD

**Issue by Majestyc2k1** [FTBTeam/Equivalent-Exchange#3]
### Mod version

1.20.4-1.0.4

### Forge / Fabric version

Neoforge 20.4.232

### Modpack & version

Creator made

### What issue are you having?

On the Transmutation table, when it learns more than 16 items, it does not create additional pages you can scroll thru to search. It only displays the top 16 items learned. The Search Bar does work as intended. 

### Steps to reproduce

NA

**Comment by gigabit101** [comment]
Can you explain what you mean by the search bar is not working correctly, Its working fine in my testing

**Comment by Majestyc2k1** [comment]
The Search Bar is working correctly. Its the circle where the item icons are. It only displays a total of 16 items, regardless of how many items have been learned over 16. There is no way to search the circle like in previous versions.

**Comment by Majestyc2k1** [comment]
I would also like to add that the smaller circle on the left doesn't do anything. In past versions, you could place an item on this circle and the Table would learn it. The only way the table learns in the current version is to place it in the Fuel Slot.

**Comment by gigabit101** [comment]
Fixed in 1.0.5
Added back putting items on the left side of the table to learn knowledge
Added back left and right page buttons
