### ISSUE TITLE
Repair Talisman not working

### ISSUE THREAD

**Issue by Majestyc2k1** [FTBTeam/Equivalent-Exchange#4]
### Mod version

1.20.4-1.0.4

### Forge / Fabric version

Neoforge 20.4.232

### Modpack & version

Creator made

### What issue are you having?

The Repair Talisman does not seem to be repairing. I had it in my inventory, on my hot bar, on my hot bar in my hand, and in the off-hand. I was wearing chain mail armor, and also tested it with a vanilla shovel. I had Force Craft tools in my inventory, but I'm not sure if you intended those to work with the Talisman. 

### Steps to reproduce

NA

**Comment by gigabit101** [comment]
The repair talisman got a little balance added to it and now requires EMC from the Klien Star to work
